### ISSUE TITLE
no support for Python 3 

### ISSUE THREAD

**Issue by meije** [josch/img2pdf#22]
Currently fails in:
- print statements lines 88-90 of jp2.py module
- implicit conversion to string line 63 of img2pdf.py

**Comment by josch** [comment]
I added Python 3 support.
Can you verify that this works for you?

**Comment by meije** [comment]
Hi,


Thank you for your prompt support.

I confirm that it is now working on my side (Python 3.4).

I can although testify that your code performs very well. I processed 100 jpeg files totaling 85.2 MB, it generated a 85.3 MB PDF file within a split second!

Thanks for sharing such a performing code and supporting it efficiently!






Sent from Surface





From: josch
Sent: ‎Wednesday‎, ‎January‎ ‎7‎, ‎2015 ‎3‎:‎57‎ ‎PM
To: josch/img2pdf
Cc: meije





I added Python 3 support.
Can you verify that this works for you?

**Comment by josch** [comment]
A new release with python3 support was made - closing.
