### ISSUE TITLE
Using output width and height options causes error on Windows

### ISSUE THREAD

**Issue by dgonyier** [josch/img2pdf#24]
Not sure if this is windows specific or not, but the following command line causes an error:

C:\> img2pdf.exe -o "output.pdf" -d 200 -x 612 -y  792  "input.jpg"

Traceback (most recent call last):
  File "C:\Python27\Scripts\img2pdf-script.py", line 9, in <module>
    load_entry_point('img2pdf==0.1.3', 'console_scripts', 'img2pdf')()
  File "C:\Python27\lib\site-packages\img2pdf.py", line 358, in main
    args.subject, args.keywords, args.colorspace, args.verbose))
  File "C:\Python27\lib\site-packages\img2pdf.py", line 287, in convert
    pdf.addimage(color, width, height, imgformat, imgdata, pdf_x, pdf_y)
UnboundLocalError: local variable 'pdf_x' referenced before assignment

**Comment by xiota** [comment]
It appears that this problem has already been fixed.

**Comment by josch** [comment]
I made a new release, can you still see this problem?

**Comment by dgonyier** [comment]
Tested same command with img2pdf (0.1.4) seems to be working ok
