### ISSUE TITLE
[Feature request] Add --version option

### ISSUE THREAD

**Issue by sahwar** [josch/img2pdf#31]
Hi, it's me again, sorry for posting so much lately! :) I hope that I'm not too annoying by doing that.

It would be nice if a simple `--version` option is added to `img2pdf` that lists the release version of the program. Maybe including the versions of the `img2pdf`'s dependencies that are reported to work is also nice to put in `--version`. It would be useful for reporting the version that one uses for issue reports.

P.S. Should I add the idea to include a detailed `man` page for the next release as a separate issue / bug report / feature request? I agreed with @josch  in the other recent feature request issue that it's good to have.

Cheers and thanks again for the great program! :)

**Comment by josch** [comment]
This is a good idea. Pull requests welcome! Otherwise I'll look into it over the next couple of days.

**Comment by sahwar** [comment]
@josch 
Thanks for considering this a good idea. I'm no programmer so I can't implement the change needed for this feature to be implemented, but if I were, I would definitely have done it. But since I'm not, all that I can offer are bug reports and feature requests/suggestions, I hope that this is also counted as a sort of contribution to the project (if only in the form of ideas, suggestions, etc.). :)

Cheers for your outstanding efforts!

**Comment by josch** [comment]
This issue should now be fixed. Please test and close this bug report if you consider the problem fixed.

Bug reports are a great contribution to any project in my eyes. One doesn't need to be a programmer to find problems or suggest new features. :)

**Comment by sahwar** [comment]
@josch 

Thanks for the kind works, likewise for the programming work done by you and the other code contributor(s)! :)

It's currently night time in my time zone and I have to go to sleep so I'll check if it works in the morning and post another post here after testing it, but I guess that it should work even without testing it yet. :D

Does the change to the code make `$ pip install img2pdf` always fetch the latest (git) version?

P.S.  Are you still planning on adding a detailed `man` page for the 0.1.7 (which will perhaps also include the implementation of https://github.com/josch/img2pdf/issues/28?) release? Will this https://github.com/josch/img2pdf/pull/32 also make it into 0.1.7? Thanks in advance for your reply.

**Comment by josch** [comment]
I'm not very familiar with pip I'm always using the packages my distribution provides instead. As far as I know, I have to manually upload a new version to pypi after every release.

I thought that for now, running help2man would be sufficient for a man page. But in the long term, a man page is on the table, yes.

Instead of #32 you probably mean #33 as the former got closed by @xiota. I don't know what the 0.1.7 release will include. The next one will be 0.1.6. I make a release once a significant new feature has made it into the codebase. And if another significant new feature makes it in shortly after that, then there will be another release. I don't think there is anything wrong with making releases often.

**Comment by sahwar** [comment]
I installed `img2pdf` from the latest git source and I can confirm that the newly implemented `--version`/`-V` option works as expected so I'm closing this issue.

I said 0.1.7 because after seeing you name the newest version `img2pdf 0.1.6~git`, I thought that the 0.1.6 release is finalized, but it seems that you're going to work on https://github.com/josch/img2pdf/pull/33 with @xiota for that release before officially releasing it (i.e. 0.1.6), i.e. committing it to pypi.

Yes, `help2man` is enough for now for producing a `man` page from `--version` and `--help` and I do agree that a full-fledged `man` page is good to have in the long term.

I'm perfectly OK with making releases often. :)
